---
title: "day2_activities"
format: html
editor: visual
---

## Part 1

```{r}
vec_1 <- c(2, 5, 9, 10, 8, 12, 1, 0)
# class of vector
class(vec_1)
# what type of variable is stored
typeof(vec_1)
# access 3rd element
vec_1_e3 <- vec_1[3]
# access 1st element
vec_1_e1 <- vec_1[1]
# access 5-7 element
vec_1_e5to7 <- vec_1[5:7]
# reassign vec 1 to character
vec_1_char <- as.character(vec_1)
vec_1_char

```

```{r}
vec_2 <- c(town = "Santa Barbara", location = "Rincon", swell = "south")
# What is the class of vector elements?
class(vec_2)
# What is the length of vec_2?
length(vec_2)
# Access the 2nd element by name and store as vec_2_e2
vec_2_e2 <- vec_2[2]
vec_2_e2
```

```{r}
df_1 <- data.frame(region = c("A", "B", "C", "D"),
                   species = c("otter", "great white", "sea lion", "gray whale"),
                   count = c(12, 2, 36, 6))
df_1
# Return the class of the entire data frame
class(df_1)
# Return the class of the species column
class(df_1[,2])
# Find the maximum value of the count() column, store as max_count
max_count <- max(df_1$count)
max_count

```

## 
